### PR TITLE
If a database is being created, import SQL to it.

### PR DESCRIPTION
**Pull request by Tebro**
If a user creates a database with the $ON_CREATE_DB environment variable
and import SQL files those files will be imported into the created
database.

Link: #63

### CODE REVIEW

**Comment by TedAvery** [comment]
:+1: This should be merged!

**Comment by murphyke** [comment]
+1 What is needed to merge this?

**Comment by Tebro** [comment]
AFAIK this just needs a maintainer to merge it.

**Comment by tifayuki** [comment]
Thank you

**Pull request merged**
